db2 UPDATE DATABASE CONFIGURATION USING LOGFILSIZ 20000
db2 alter bufferpool IBMDEFAULTBP IMMEDIATE SIZE 15000 AUTOMATIC
db2 UPDATE DATABASE MANAGER CONFIGURATION USING INTRA_PARALLEL YES
db2 UPDATE DATABASE MANAGER CONFIGURATION USING INTRA_PARALLEL ANY
db2 UPDATE DB CFG USING DFT_DEGREE ANY
db2 UPDATE DB CONFIG USING AUTO_MAINT ON AUTO_TBL_MAINT ON AUTO_RUNSTATS ON
