SELECT * WHERE {
	SERVICE <http://9.12.235.45:9999/blazegraph/namespace/bjdiag/sparql> {
		SELECT ?date (AVG(?value) AS ?avgval) WHERE {
  		?x <http://www.ibm.com/health/bjdiag/PM25TBL#DATE> ?date;
    	  <http://www.ibm.com/health/bjdiag/PM25TBL#VALUE> ?value
		} GROUP BY ?date
    } 
}
