SELECT * WHERE {
 SERVICE <http://9.12.235.45:9999/blazegraph/namespace/bjdiag/sparql> 
 { 
   SELECT ?date (COUNT(DISTINCT ?empi) AS ?opcnt) WHERE {
        ?x <http://www.ibm.com/health/bjdiag/DIAG_OUTPATIENT#EMPI> ?empi .
		?x  <http://www.ibm.com/health/bjdiag/DIAG_OUTPATIENT#DATE> ?date ;
			<http://www.ibm.com/health/bjdiag/DIAG_OUTPATIENT#DIAG_NAME> "胸闷" 
    } GROUP BY ?date  
 }
}