SELECT * WHERE {	
	SERVICE <http://9.12.235.45:9999/blazegraph/namespace/bjdiag/sparql> {
		SELECT ?date ?diag_code (COUNT(DISTINCT ?empi) AS ?opcnt) WHERE {
        ?x <http://www.ibm.com/health/bjdiag/DIAG_OUTPATIENT#EMPI> ?empi ;
		    <http://www.ibm.com/health/bjdiag/DIAG_OUTPATIENT#DATE> ?date ;
			<http://www.ibm.com/health/bjdiag/DIAG_OUTPATIENT#DIAG_NAME> ?diag_code
		FILTER (?diag_code = "胸闷" 
			 || ?diag_code = "胸痛"
			 || ?diag_code = "肺部感染" )
	   } GROUP BY ?date ?diag_code  
    } 
}

