
prefix fn: <http://localhost:8083/>
prefix fn2: <http://localhost:8888/>
prefix x: <http://www.drugbank.ca>
prefix xs: <http://www.w3.org/2001/XMLSchema>

function fn:getDrugBankNames GET ( -> ?x ) 
service fn:getDrugBankNames [ ] -> "//x:row" :: "./x:drug" "xs:string"

function fn:getDrugSMILES GET ( ?x -> ?y ) 
service fn:getSMILES [ "drugName" -> ?x ] -> "//x:row" :: "./x:drug" "xs:string" "./x:smiles" "xs:string" 

select distinct * where {

BIND( fn:getDrugBankNames() AS ( ?drug ) )

BIND( fn:getDrugSMILES( ?drug ) AS ( ?drug ?SMILES ) )

}
