
prefix fn: <http://localhost:8083/>
prefix x: <http://www.drugbank.ca>
prefix xs: <http://www.w3.org/2001/XMLSchema>

function fn:getDrugBankNames GET ( -> ?x ) 
service fn:getDrugBankNames [ ] -> "//x:row" :: "./x:drug" "xs:string"

select ?drug ?drug1 where {

BIND( fn:getDrugBankNames() AS ( ?drug ) )

BIND( fn:getDrugBankNames() AS ( ?drug1 ) )

}
