
prefix fn: <http://localhost:8083/>
prefix x: <http://www.drugbank.ca>
prefix xs: <http://www.w3.org/2001/XMLSchema>

function fn:getDrugBank GET ( -> ?x ?y ?z ) 
service fn:getDrugBank [ ] -> "//x:row" :: "./x:drug" "xs:string" "./x:id" "xs:string" "./x:action" "xs:string"

select * where {

BIND( fn:getDrugBank() AS ( ?drug ?id ?action ) )

}
