
prefix fn: <http://9.12.235.45:8083/>
prefix x: <http://www.drugbank.ca>
prefix xs: <http://www.w3.org/2001/XMLSchema>

function fn:getDrugBankNames GET ( -> ?x ) 
service fn:getDrugBankNames [ ] -> "//x:row" :: "./x:drug" "xs:string"

function fn:getTransportersGet GET ( ?x -> ?y ) 
service fn:getDrugTransporters [ "drugName" -> ?x ] -> "//x:row" :: "./x:drug" "xs:string" "./x:transporter" "xs:string" 

function fn:getTransportersPost ( ?drug -> ?targets ) 
table fn:getTransporters [ "funcData" -> post data ] -> "//x:row" :: "./x:drug" "xs:string" "./x:transporter" "xs:string" 

select ?drug ?targets where {

BIND( fn:getDrugBankNames() AS ( ?drug ) )

BIND( fn:getTransportersPost( ?drug ) AS ( ?drug ?targets ) )

}
